"""Generate a Dart source file embedding SEGUIEMJ.TTF pseudo-emoji ranges.

Only BMP symbol codepoints (U+2190..U+2BFF + a handful of CJK symbols) are
embedded - these are the "pseudo-emoji" that third-party CJK fonts tend to
hijack with monochrome vector glyphs. True emoji (U+1F300+) is already handled
by flame_barrage's EmojiAtlas.
"""

import json
import sys
from pathlib import Path


def main() -> None:
    ranges_path = Path("tool/emoji_codepoints_ranges.txt")
    if not ranges_path.exists():
        print(f"ERROR: {ranges_path} not found. Run extract_emoji_codepoints.py first.", file=sys.stderr)
        sys.exit(1)

    # Parse the ranges file. Each line: "0xHHHH, 0xHHHH,  # c..c  Block"
    # We only keep ranges that fall within U+2190..U+2BFF, plus CJK symbol codepoints.
    kept: list[tuple[int, int]] = []
    for line in ranges_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # "0x2190, 0x21FF,  # ←..⇿  Arrows"
        parts = line.split(",")
        if len(parts) < 2:
            continue
        start = int(parts[0].strip(), 0)
        end = int(parts[1].strip(), 0)

        # Keep ranges within U+2190..U+2BFF (symbol/pseudo-emoji core zone)
        if 0x2190 <= start <= 0x2BFF:
            kept.append((start, end))
            continue

        # Also keep a handful of CJK symbol codepoints that Segoe UI Emoji renders as emoji
        if start == 0x3030 or start == 0x303D:
            kept.append((start, end))
            continue
        if 0x3244 <= start <= 0x3299:
            kept.append((start, end))
            continue

    kept.sort()

    # Generate compact Dart source
    lines = []
    lines.append("// AUTO-GENERATED by tool/gen_seg_emoji_ranges.py - DO NOT EDIT.")
    lines.append("// Source: SEGUIEMJ.TTF (Segoe UI Emoji) cmap, filtered to U+2190..U+2BFF + CJK symbols.")
    lines.append("// These codepoints are the 'pseudo-emoji' that third-party CJK fonts commonly")
    lines.append("// hijack with monochrome vector glyphs, preventing fallback to Segoe UI Emoji.")
    lines.append("")
    lines.append("/// Closed [start, end] codepoint ranges that Segoe UI Emoji renders as color emoji.")
    lines.append("///")
    lines.append("/// Only BMP symbol ranges are listed. True emoji (U+1F300+) is handled by")
    lines.append("/// flame_barrage's EmojiAtlas sprite/emoji fragments and does not need to be")
    lines.append("/// listed here.")
    lines.append("const List<(int, int)> kSegoeEmojiPseudoRanges = [")
    for start, end in kept:
        if start == end:
            lines.append(f"  (0x{start:04X}, 0x{end:04X}),")
        else:
            lines.append(f"  (0x{start:04X}, 0x{end:04X}),")
    lines.append("];")
    lines.append("")
    lines.append("/// Returns true if [codepoint] is a pseudo-emoji codepoint covered by")
    lines.append("/// Segoe UI Emoji and should be rendered with that font instead of the")
    lines.append("/// user-selected font family.")
    lines.append("bool isSegoeEmojiCodepoint(int codepoint) {")
    lines.append("  // Binary search over kSegoeEmojiPseudoRanges.")
    lines.append("  int lo = 0;")
    lines.append("  int hi = kSegoeEmojiPseudoRanges.length - 1;")
    lines.append("  while (lo <= hi) {")
    lines.append("    final mid = (lo + hi) >> 1;")
    lines.append("    final (start, end) = kSegoeEmojiPseudoRanges[mid];")
    lines.append("    if (codepoint < start) {")
    lines.append("      hi = mid - 1;")
    lines.append("    } else if (codepoint > end) {")
    lines.append("      lo = mid + 1;")
    lines.append("    } else {")
    lines.append("      return true;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return false;")
    lines.append("}")
    lines.append("")

    out_path = Path("pure_live/plugins/flame_barrage/lib/src/layout/seg_emoji_ranges.dart")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path} ({len(kept)} ranges)")


if __name__ == "__main__":
    main()
